version: 2
updates:
  # Python dependencies via Poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 10
    assignees:
      - "sjefsharp"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    groups:
      # Group autogen packages together
      autogen:
        patterns:
          - "autogen*"
      # Group testing dependencies
      testing:
        patterns:
          - "pytest*"
          - "types-*"
      # Group linting/formatting tools
      code-quality:
        patterns:
          - "ruff"
          - "mypy"
          - "bandit*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    assignees:
      - "sjefsharp"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Security updates (higher priority)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    assignees:
      - "sjefsharp"
    commit-message:
      prefix: "security"
      include: "scope"
    labels:
      - "security"
      - "dependencies"
