repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        language_version: python3.13
        additional_dependencies:
          [types-requests, types-requests-oauthlib, types-redis, autogen-ext]
        args: [--enable-error-code=misc]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
        args: [--fix]
        language_version: python3.13
      - id: ruff-format
        language_version: python3.13
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        exclude: ^tests/
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        args:
          [
            "--cov=src/agentic_crypto_influencer",
            "--cov-report=term-missing",
            "--cov-fail-under=80",
          ]
