repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        language_version: python3.13
        additional_dependencies:
          [
            types-requests==2.32.0.*,
            types-requests-oauthlib==1.3.0.*,
            types-redis==4.6.0.*,
            types-flask==1.1.6.*,
            autogen-ext==0.7.4.*,
          ]
        args:
          [
            "--ignore-missing-imports",
            "--strict",
            "--no-warn-unused-ignores",
            "--namespace-packages",
          ]
        files: ^src/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
        args: [--fix]
        language_version: python3.13
      - id: ruff-format
        language_version: python3.13
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-s", "B101,B102,B404,B603"]
        language_version: python3.13
        exclude: ^tests/
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        args:
          [
            "--cov=src/agentic_crypto_influencer",
            "--cov-report=term-missing",
            "--cov-fail-under=80",
          ]
