[project]
name = "agentic-crypto-influencer"
version = "0.1.0"
description = ""
authors = [
    {name = "Sjef Jenniskens",email = "14937399+sjefsharp@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff (>=0.12.10,<0.13.0)",
    "black (>=25.1.0,<26.0.0)",
    "mypy (>=1.17.1,<2.0.0)",
    "pre-commit (>=4.3.0,<5.0.0)",
    "autogen-agentchat (>=0.7.4,<0.8.0)",
    "autogen-core (>=0.7.4,<0.8.0)",
    "autogen-gemini (>=0.0.1,<0.0.2)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "autogen-ext (>=0.7.4,<0.8.0)",
    "google-genai (>=1.31.0,<2.0.0)",
    "requests-oauthlib (>=2.0.0,<3.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "isort (>=6.0.1,<7.0.0)",
    "openai (>=1.101.0,<2.0.0)",
    "tiktoken (>=0.11.0,<0.12.0)",
    "flask (>=3.1.2,<4.0.0)",
    "types-requests (>=2.32.4.20250809,<3.0.0.0)",
    "pytest (>=8.4.1,<9.0.0)",
    "types-redis (>=4.6.0.20241004,<5.0.0.0)",
    "redis (>=6.4.0,<7.0.0)",
    "python-bitvavo-api (>=1.4.3,<2.0.0)",
]

[tool.poetry]
packages = [{include = "agentic_crypto_influencer", from = "src"}]


[tool.poetry.group.dev.dependencies]
types-requests = "^2.32.4.20250809"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
