[project]
name = "agentic-crypto-influencer"
version = "0.1.0"
description = ""
authors = [
    {name = "Sjef Jenniskens",email = "14937399+sjefsharp@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff (>=0.12.10,<0.13.0)",
    "black (>=25.1.0,<26.0.0)",
    "mypy (>=1.17.1,<2.0.0)",
    "pre-commit (>=4.3.0,<5.0.0)"
]

[tool.poetry]
packages = [{include = "agentic_crypto_influencer", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
