name: CD

on:
  push:
    tags:
      - "v*.*.*"
  release:
    types: [published]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Set up test environment
        run: |
          # Use a dedicated .env file for tests to keep it clean
          echo "REDIS_URL=redis://localhost:6379" >> .env
          echo "X_URL=https://api.twitter.com" >> .env
          echo "X_TWEETS_ENDPOINT=/2/tweets" >> .env
          echo "X_AUTHORIZE_ENDPOINT=/oauth/authorize" >> .env
          echo "X_TOKEN_ENDPOINT=/oauth/access_token" >> .env
          echo "X_PERSONALIZED_TRENDS_ENDPOINT=/1.1/trends/available.json" >> .env
          # Set test values for missing secrets (secrets are automatically available as env vars)
          [ -z "$GOOGLE_API_KEY" ] && echo "GOOGLE_API_KEY=test_key" >> .env || true
          [ -z "$GOOGLE_GENAI_API_KEY" ] && echo "GOOGLE_GENAI_API_KEY=test_key" >> .env || true
          [ -z "$X_API_KEY" ] && echo "X_API_KEY=test_key" >> .env || true
          [ -z "$X_API_SECRET" ] && echo "X_API_SECRET=test_secret" >> .env || true
          [ -z "$X_ACCESS_TOKEN" ] && echo "X_ACCESS_TOKEN=test_token" >> .env || true
          [ -z "$X_ACCESS_TOKEN_SECRET" ] && echo "X_ACCESS_TOKEN_SECRET=test_secret" >> .env || true
          [ -z "$BITVAVO_API_KEY" ] && echo "BITVAVO_API_KEY=test_key" >> .env || true
          [ -z "$BITVAVO_API_SECRET" ] && echo "BITVAVO_API_SECRET=test_secret" >> .env || true

      - name: Run tests with environment variables
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_GENAI_API_KEY: ${{ secrets.GOOGLE_GENAI_API_KEY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          BITVAVO_API_KEY: ${{ secrets.BITVAVO_API_KEY }}
          BITVAVO_API_SECRET: ${{ secrets.BITVAVO_API_SECRET }}
        run: poetry run pytest --cov=src/agentic_crypto_influencer --cov-fail-under=80

      - name: Build package
        run: poetry build

      - name: Create GitHub release notes
        if: github.event_name == 'release'
        run: |
          echo "🎉 Release ${{ github.event.release.tag_name }} published!" >> release_notes.md
          echo "" >> release_notes.md
          echo "## What's Changed" >> release_notes.md
          echo "" >> release_notes.md
          git log --pretty=format:"- %s (%h)" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> release_notes.md

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs: [build_and_test]

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging environment"
          # Add your staging deployment commands here
          # For example: docker build, docker push, kubectl apply, etc.

  deploy-production:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: [build_and_test]

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Deploy to production
        run: |
          echo "🎯 Deploying to production environment"
          # Add your production deployment commands here
          # For example: docker build, docker push, kubectl apply, etc.
