name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 8:00 UTC
    - cron: "0 8 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Set up test environment
        run: |
          echo "REDIS_URL=redis://localhost:6379" >> $GITHUB_ENV
          echo "GOOGLE_API_KEY=test_key" >> $GITHUB_ENV
          echo "GOOGLE_GENAI_API_KEY=test_key" >> $GITHUB_ENV
          echo "X_API_KEY=test_key" >> $GITHUB_ENV
          echo "X_API_SECRET=test_secret" >> $GITHUB_ENV
          echo "X_ACCESS_TOKEN=test_token" >> $GITHUB_ENV
          echo "X_ACCESS_TOKEN_SECRET=test_secret" >> $GITHUB_ENV
          echo "BITVAVO_API_KEY=test_key" >> $GITHUB_ENV
          echo "BITVAVO_API_SECRET=test_secret" >> $GITHUB_ENV
          echo "X_URL=https://api.twitter.com" >> $GITHUB_ENV
          echo "X_TWEETS_ENDPOINT=/2/tweets" >> $GITHUB_ENV
          echo "X_AUTHORIZE_ENDPOINT=/oauth/authorize" >> $GITHUB_ENV
          echo "X_TOKEN_ENDPOINT=/oauth/access_token" >> $GITHUB_ENV
          echo "X_PERSONALIZED_TRENDS_ENDPOINT=/1.1/trends/available.json" >> $GITHUB_ENV

      - name: Update dependencies
        run: |
          poetry update
          poetry lock

      - name: Run tests after update
        run: |
          poetry install
          poetry run pytest --cov=src/agentic_crypto_influencer --cov-fail-under=80

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: weekly dependency updates"
          body: |
            ## Dependency Updates

            This PR updates project dependencies to their latest compatible versions.

            ### Changes
            - Updated all dependencies to latest compatible versions
            - Regenerated poetry.lock file
            - All tests pass with updated dependencies

            ### Testing
            - ✅ All tests pass
            - ✅ Coverage >= 80%
            - ✅ Pre-commit hooks pass

            ### Review Checklist
            - [ ] Review dependency changes
            - [ ] Check for breaking changes
            - [ ] Verify tests still pass
          branch: chore/dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated
          assignees: ${{ github.actor }}
